SelectedFolders:
- D:\SourceButler
- D:\SourceButler\SourceButler
- D:\SourceButler\SourceButler\Models
- D:\SourceButler\SourceButler\ViewModels
SelectedExtensions:
- .cs
- .xaml
- .csproj
- .sln
LastRootDirectory: D:\SourceButler
